#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <dirent.h>
#include <sys/stat.h>

/*
 * Detroit: The Accomplice – Terminal Interactive Game
 *
 * This program parses a large interactive story from a text file and presents
 * it as a choose‑your‑own‑adventure game in the terminal.  Each chapter
 * contains descriptive prose followed by a series of numbered choices.  The
 * player navigates through the chapters by selecting options.  Progress
 * persists between sessions via simple text files: one recording the
 * narrative path and another recording relationship updates.  A global
 * summary keeps track of which endings have been reached for each act.
 *
 * Features:
 *  - Parses all chapters from the provided story file on startup.  Each
 *    chapter records its title, prose and any available choices.  Choices
 *    automatically link to their destination chapters by matching the
 *    choice label with the next chapter title.
 *  - Modern, coloured terminal interface using ANSI escape codes.  The
 *    player’s chosen name replaces all instances of “YN600” in the text.
 *  - Save system allowing multiple named save slots.  Each save writes two
 *    files: one for the narrative path and one for relationship updates.
 *    A separate global file records which endings (within each act) have
 *    been achieved across all saves.
 *  - Relationship and ending information is parsed from the story’s
 *    “Chapter End Notes” section.  Lines such as “ANDRE: TRUSTED”,
 *    “ACT I - COMPLETE” and “ENDING [1/3]” are extracted and logged.
 *
 * Author: Generated by ChatGPT for demonstration purposes.
 */

#define STORY_FILE "Detroit_The_Accomplice.txt"
#define SAVE_DIR   "saves"
#define GLOBAL_ENDINGS_FILE SAVE_DIR "/global_endings.txt"
#define MAX_LINE_LENGTH 4096

/* ANSI colour codes for a modern terminal appearance */
#define ANSI_RESET      "\033[0m"
#define ANSI_BOLD       "\033[1m"
#define ANSI_UNDERLINE  "\033[4m"
#define ANSI_RED        "\033[31m"
#define ANSI_GREEN      "\033[32m"
#define ANSI_YELLOW     "\033[33m"
#define ANSI_BLUE       "\033[34m"
#define ANSI_MAGENTA    "\033[35m"
#define ANSI_CYAN       "\033[36m"
#define ANSI_WHITE      "\033[37m"

/* Utility structure to hold a single choice */
typedef struct {
    char symbol;          /* The PlayStation‑style symbol character (e.g. O, X, Δ, □) */
    char *label;          /* The human readable choice text extracted from the story */
    int destChapter;      /* Index of the chapter this choice leads to (filled after parsing) */
} Choice;

/* Structure representing a chapter in the CYOA */
typedef struct {
    int number;           /* Sequential identifier extracted from “Chapter N:” */
    char *title;          /* Title of the chapter (e.g. “AWAKENING” or “GO TO SOURCE”) */
    char *text;           /* Narrative text (with newline separators) */
    Choice *choices;      /* Dynamic array of choices available in this chapter */
    int choiceCount;      /* Number of choices */
    char **infos;         /* Array of informational lines (relationships, act completions, endings) */
    int infoCount;        /* Number of info lines */
    /* For endings */
    char *endingAct;      /* Roman numeral of the act if this chapter finishes an act */
    int endingNumber;     /* Which ending number (n) within its act */
    int endingTotal;      /* Total endings (m) within its act */
} Chapter;

/* Dynamic container for chapters */
typedef struct {
    Chapter *chapters;
    int count;
    int capacity;
} ChapterList;

/* String utility: trim whitespace from start and end */
static char *trim(char *str) {
    if (!str) return NULL;
    size_t len = strlen(str);
    while (len > 0 && isspace((unsigned char)str[len - 1])) {
        str[--len] = '\0';
    }
    size_t start = 0;
    while (str[start] && isspace((unsigned char)str[start])) {
        start++;
    }
    return str + start;
}

/* Convert a string to uppercase (in place) */
static void strtoupper(char *str) {
    while (*str) {
        *str = (char)toupper((unsigned char)*str);
        str++;
    }
}

/* Replace all occurrences of a substring within a string.  Returns a newly
 * allocated string.  Caller must free the result.  If no replacements
 * occur, the original string is copied. */
static char *replace_substr(const char *source, const char *target, const char *replacement) {
    if (!source || !target || !replacement) return NULL;
    size_t srcLen = strlen(source);
    size_t tgtLen = strlen(target);
    if (tgtLen == 0) {
        char *dup = strdup(source);
        return dup;
    }
    /* First pass: count occurrences */
    size_t count = 0;
    const char *p = source;
    while ((p = strstr(p, target)) != NULL) {
        count++;
        p += tgtLen;
    }
    /* Allocate memory for the new string */
    size_t repLen = strlen(replacement);
    size_t newLen = srcLen + count * (repLen - tgtLen);
    char *result = (char *)malloc(newLen + 1);
    if (!result) return NULL;
    /* Second pass: build the new string */
    const char *srcPtr = source;
    char *dstPtr = result;
    while ((p = strstr(srcPtr, target)) != NULL) {
        size_t bytes = p - srcPtr;
        memcpy(dstPtr, srcPtr, bytes);
        dstPtr += bytes;
        memcpy(dstPtr, replacement, repLen);
        dstPtr += repLen;
        srcPtr = p + tgtLen;
    }
    /* Copy the remainder */
    strcpy(dstPtr, srcPtr);
    return result;
}

/* Helper to append a line to a growing string buffer.  Grows the buffer
 * automatically.  Returns the new buffer pointer. */
static char *append_line(char *buffer, size_t *len, size_t *cap, const char *line) {
    size_t lineLen = strlen(line);
    /* Ensure there is space for the new line and a null terminator */
    if (*len + lineLen + 1 > *cap) {
        size_t newCap = (*cap == 0 ? 256 : *cap * 2);
        while (newCap < *len + lineLen + 1) newCap *= 2;
        char *newBuf = (char *)realloc(buffer, newCap);
        if (!newBuf) {
            free(buffer);
            return NULL;
        }
        buffer = newBuf;
        *cap = newCap;
    }
    memcpy(buffer + *len, line, lineLen);
    *len += lineLen;
    buffer[*len] = '\0';
    return buffer;
}

/* Initialise an empty ChapterList */
static void init_chapter_list(ChapterList *cl) {
    cl->chapters = NULL;
    cl->count = 0;
    cl->capacity = 0;
}

/* Finalise a ChapterList and free all allocated memory */
static void free_chapter_list(ChapterList *cl) {
    if (!cl) return;
    for (int i = 0; i < cl->count; ++i) {
        Chapter *ch = &cl->chapters[i];
        free(ch->title);
        free(ch->text);
        for (int j = 0; j < ch->choiceCount; ++j) {
            free(ch->choices[j].label);
        }
        free(ch->choices);
        for (int j = 0; j < ch->infoCount; ++j) {
            free(ch->infos[j]);
        }
        free(ch->infos);
        free(ch->endingAct);
    }
    free(cl->chapters);
    cl->chapters = NULL;
    cl->count = 0;
    cl->capacity = 0;
}

/* Add a new chapter to the chapter list */
static Chapter *add_chapter(ChapterList *cl) {
    if (cl->count >= cl->capacity) {
        int newCap = (cl->capacity == 0 ? 16 : cl->capacity * 2);
        Chapter *newArr = (Chapter *)realloc(cl->chapters, newCap * sizeof(Chapter));
        if (!newArr) {
            return NULL;
        }
        cl->chapters = newArr;
        cl->capacity = newCap;
    }
    Chapter *ch = &cl->chapters[cl->count++];
    memset(ch, 0, sizeof(Chapter));
    return ch;
}

/* Sanitize a chapter title by removing surrounding brackets and spaces */
static char *sanitize_title(char *raw) {
    char *title = trim(raw);
    /* Remove enclosing square brackets if present */
    size_t len = strlen(title);
    if (len > 0 && title[0] == '[' && title[len - 1] == ']') {
        title[len - 1] = '\0';
        title++;
        title = trim(title);
    }
    return title;
}

/* Convert a Roman numeral string (e.g. "I", "II", "III") to an integer.  Returns
 * -1 on failure. */
static int roman_to_int(const char *roman) {
    int total = 0;
    int prev = 0;
    for (const char *p = roman; *p; ++p) {
        int val = 0;
        switch (toupper((unsigned char)*p)) {
            case 'I': val = 1; break;
            case 'V': val = 5; break;
            case 'X': val = 10; break;
            case 'L': val = 50; break;
            case 'C': val = 100; break;
            case 'D': val = 500; break;
            case 'M': val = 1000; break;
            default: return -1;
        }
        if (val > prev) {
            total += val - 2 * prev;
        } else {
            total += val;
        }
        prev = val;
    }
    return total;
}

/* Parse the entire story file and fill the ChapterList.  Also collects
 * information about acts and endings (returning maximum endings for each act
 * via output parameters).  Returns 0 on success, non‑zero on failure. */
static int parse_story(ChapterList *cl, int verbose) {
    FILE *fp = fopen(STORY_FILE, "r");
    if (!fp) {
        fprintf(stderr, "Error: Unable to open story file %s\n", STORY_FILE);
        return -1;
    }
    char *line = NULL;
    size_t lineCap = 0;
    ssize_t nread;
    Chapter *current = NULL;
    /* Buffer for lines belonging to current chapter */
    char **lines = NULL;
    size_t linesCount = 0;
    size_t linesCap = 0;
    while ((nread = getline(&line, &lineCap, fp)) != -1) {
        /* Remove newline characters */
        if (nread > 0 && (line[nread - 1] == '\n' || line[nread - 1] == '\r')) {
            /* trim trailing CR/LF */
            while (nread > 0 && (line[nread - 1] == '\n' || line[nread - 1] == '\r')) {
                line[--nread] = '\0';
            }
        }
        /* Detect new chapter heading: lines beginning with "Chapter " */
        if (strncmp(line, "Chapter ", 8) == 0) {
            /* If we were already reading a chapter, finalise it */
            if (current) {
                /* Combine lines into chapter fields */
                size_t textLen = 0;
                size_t textCap = 0;
                char *textBuf = NULL;
                Choice *choices = NULL;
                int choiceCount = 0;
                int choiceCap = 0;
                char **infos = NULL;
                int infoCount = 0;
                int infoCap = 0;
                char *endingAct = NULL;
                int endingNumber = 0;
                int endingTotal = 0;
                int parsingNotes = 0;
                for (size_t li = 0; li < linesCount; ++li) {
                    char *ln = lines[li];
                    /* Skip empty lines or whitespace lines but keep as part of narrative */
                    char *trimLine = trim(ln);
                    /* Recognise Chapter Notes section; skip the note header itself */
                    if (strcmp(trimLine, "Chapter Notes") == 0) {
                        parsingNotes = 1;
                        continue;
                    }
                    if (parsingNotes) {
                        /* Skip the default “See the end of the chapter for notes” line */
                        if (strncmp(trimLine, "See the end", 12) == 0) {
                            continue;
                        }
                        /* After Chapter Notes we often see a blank line and the story begins; do not treat Chapter Notes differently beyond skipping the header */
                    }
                    /* Recognise info lines */
                    int isInfo = 0;
                    /* ACT lines */
                    if (strncmp(trimLine, "ACT ", 4) == 0) {
                        isInfo = 1;
                        /* Extract act Roman numeral */
                        /* Format: ACT X - COMPLETE */
                        /* We'll store the whole line as info; parse ending info separately later */
                    } else if (strncasecmp(trimLine, "ENDING", 6) == 0) {
                        isInfo = 1;
                        /* Format: ENDING [n/m] or Ending [n/m] */
                        /* Extract numbers */
                        const char *bracket = strchr(trimLine, '[');
                        if (bracket) {
                            int n = 0, m = 0;
                            sscanf(bracket + 1, "%d/%d", &n, &m);
                            if (n > 0 && m > 0) {
                                endingNumber = n;
                                endingTotal = m;
                                /* the act will be parsed from other info lines in this chapter */
                            }
                        }
                    } else {
                        /* Relationship lines: pattern "NAME: STATUS" where NAME is uppercase */
                        char *colon = strchr(trimLine, ':');
                        if (colon) {
                            /* Check that characters before colon are uppercase or space */
                            int valid = 1;
                            for (char *c = trimLine; c < colon; ++c) {
                                if (!isupper((unsigned char)*c) && *c != ' ' && *c != '-') {
                                    valid = 0;
                                    break;
                                }
                            }
                            if (valid) {
                                isInfo = 1;
                            }
                        }
                    }
                    if (isInfo) {
                        if (infoCount >= infoCap) {
                            int newCap = (infoCap == 0 ? 4 : infoCap * 2);
                            char **tmp = (char **)realloc(infos, newCap * sizeof(char *));
                            if (!tmp) {
                                /* memory error */
                                continue;
                            }
                            infos = tmp;
                            infoCap = newCap;
                        }
                        infos[infoCount++] = strdup(trimLine);
                        /* Extract ending act from “ACT X - COMPLETE” */
                        if (strncmp(trimLine, "ACT ", 4) == 0) {
                            /* Copy the Roman numeral portion */
                            const char *dash = strchr(trimLine, '-');
                            if (dash) {
                                size_t len = (size_t)(dash - (trimLine + 4));
                                char *act = (char *)malloc(len + 1);
                                if (act) {
                                    strncpy(act, trimLine + 4, len);
                                    act[len] = '\0';
                                    /* Trim trailing spaces */
                                    char *actTrim = trim(act);
                                    /* Convert to uppercase for consistency */
                                    strtoupper(actTrim);
                                    endingAct = strdup(actTrim);
                                    free(act);
                                }
                            }
                        }
                        continue;
                    }
                    /* Recognise choice lines: lines with pattern "[symbol][label]" */
                    if (trimLine[0] == '[') {
                        /* search for closing bracket of symbol */
                        char *close1 = strchr(trimLine, ']');
                        if (close1 && close1[1] == '[') {
                            char symChar = trimLine[1];
                            char *close2 = strchr(close1 + 1, ']');
                            if (close2) {
                                size_t labLen = (size_t)(close2 - (close1 + 2));
                                char *lab = (char *)malloc(labLen + 1);
                                strncpy(lab, close1 + 2, labLen);
                                lab[labLen] = '\0';
                                /* create choice */
                                if (choiceCount >= choiceCap) {
                                    int newCap = (choiceCap == 0 ? 4 : choiceCap * 2);
                                    Choice *tmp = (Choice *)realloc(choices, newCap * sizeof(Choice));
                                    if (!tmp) {
                                        /* memory error; skip adding choice */
                                        free(lab);
                                    } else {
                                        choices = tmp;
                                        choiceCap = newCap;
                                        choices[choiceCount].symbol = symChar;
                                        choices[choiceCount].label = lab;
                                        choices[choiceCount].destChapter = -1;
                                        choiceCount++;
                                    }
                                } else {
                                    choices[choiceCount].symbol = symChar;
                                    choices[choiceCount].label = lab;
                                    choices[choiceCount].destChapter = -1;
                                    choiceCount++;
                                }
                                continue;
                            }
                        }
                    }
                    /* Otherwise treat as narrative text */
                    /* Append the original line with a newline */
                    char *lineWithNL;
                    asprintf(&lineWithNL, "%s\n", ln);
                    textBuf = append_line(textBuf, &textLen, &textCap, lineWithNL);
                    free(lineWithNL);
                }
                /* Assign collected data to current chapter */
                current->text = textBuf ? textBuf : strdup("");
                current->choices = choices;
                current->choiceCount = choiceCount;
                current->infos = infos;
                current->infoCount = infoCount;
                current->endingAct = endingAct;
                current->endingNumber = endingNumber;
                current->endingTotal = endingTotal;
                /* Reset lines buffer */
                for (size_t li = 0; li < linesCount; ++li) {
                    free(lines[li]);
                }
                free(lines);
                lines = NULL;
                linesCount = 0;
                linesCap = 0;
            }
            /* Start a new chapter */
            current = add_chapter(cl);
            if (!current) {
                fprintf(stderr, "Error: Unable to allocate memory for new chapter\n");
                free(line);
                fclose(fp);
                return -1;
            }
            /* parse chapter header: "Chapter N: TITLE" */
            char *header = line + 8; /* skip "Chapter " */
            /* Extract the number before the colon */
            char *colon = strchr(header, ':');
            if (colon) {
                *colon = '\0';
                current->number = atoi(header);
                char *title = colon + 1;
                title = trim(title);
                title = sanitize_title(title);
                current->title = strdup(title);
            } else {
                current->number = 0;
                current->title = strdup(trim(header));
            }
            continue;
        }
        /* Not a new chapter: accumulate lines */
        if (!current) {
            /* Skip lines before the first chapter */
            continue;
        }
        if (linesCount >= linesCap) {
            size_t newCap = (linesCap == 0 ? 32 : linesCap * 2);
            char **tmp = (char **)realloc(lines, newCap * sizeof(char *));
            if (!tmp) {
                fprintf(stderr, "Error: Memory allocation failed while parsing\n");
                free(line);
                fclose(fp);
                return -1;
            }
            lines = tmp;
            linesCap = newCap;
        }
        lines[linesCount++] = strdup(line);
    }
    /* Finalise last chapter if any */
    if (current) {
        size_t textLen = 0;
        size_t textCap = 0;
        char *textBuf = NULL;
        Choice *choices = NULL;
        int choiceCount = 0;
        int choiceCap = 0;
        char **infos = NULL;
        int infoCount = 0;
        int infoCap = 0;
        char *endingAct = NULL;
        int endingNumber = 0;
        int endingTotal = 0;
        int parsingNotes = 0;
        for (size_t li = 0; li < linesCount; ++li) {
            char *ln = lines[li];
            char *trimLine = trim(ln);
            if (strcmp(trimLine, "Chapter Notes") == 0) {
                parsingNotes = 1;
                continue;
            }
            if (parsingNotes) {
                if (strncmp(trimLine, "See the end", 12) == 0) {
                    continue;
                }
            }
            int isInfo = 0;
            if (strncmp(trimLine, "ACT ", 4) == 0) {
                isInfo = 1;
            } else if (strncasecmp(trimLine, "ENDING", 6) == 0) {
                isInfo = 1;
                const char *bracket = strchr(trimLine, '[');
                if (bracket) {
                    int n = 0, m = 0;
                    sscanf(bracket + 1, "%d/%d", &n, &m);
                    if (n > 0 && m > 0) {
                        endingNumber = n;
                        endingTotal = m;
                    }
                }
            } else {
                char *colon = strchr(trimLine, ':');
                if (colon) {
                    int valid = 1;
                    for (char *c = trimLine; c < colon; ++c) {
                        if (!isupper((unsigned char)*c) && *c != ' ' && *c != '-') {
                            valid = 0;
                            break;
                        }
                    }
                    if (valid) isInfo = 1;
                }
            }
            if (isInfo) {
                if (infoCount >= infoCap) {
                    int newCap = (infoCap == 0 ? 4 : infoCap * 2);
                    char **tmp = (char **)realloc(infos, newCap * sizeof(char *));
                    if (!tmp) {
                        continue;
                    }
                    infos = tmp;
                    infoCap = newCap;
                }
                infos[infoCount++] = strdup(trimLine);
                if (strncmp(trimLine, "ACT ", 4) == 0) {
                    const char *dash = strchr(trimLine, '-');
                    if (dash) {
                        size_t len = (size_t)(dash - (trimLine + 4));
                        char *act = (char *)malloc(len + 1);
                        if (act) {
                            strncpy(act, trimLine + 4, len);
                            act[len] = '\0';
                            char *actTrim = trim(act);
                            strtoupper(actTrim);
                            endingAct = strdup(actTrim);
                            free(act);
                        }
                    }
                }
                continue;
            }
            if (trimLine[0] == '[') {
                char *close1 = strchr(trimLine, ']');
                if (close1 && close1[1] == '[') {
                    char symChar = trimLine[1];
                    char *close2 = strchr(close1 + 1, ']');
                    if (close2) {
                        size_t labLen = (size_t)(close2 - (close1 + 2));
                        char *lab = (char *)malloc(labLen + 1);
                        strncpy(lab, close1 + 2, labLen);
                        lab[labLen] = '\0';
                        if (choiceCount >= choiceCap) {
                            int newCap = (choiceCap == 0 ? 4 : choiceCap * 2);
                            Choice *tmp = (Choice *)realloc(choices, newCap * sizeof(Choice));
                            if (!tmp) {
                                free(lab);
                            } else {
                                choices = tmp;
                                choiceCap = newCap;
                                choices[choiceCount].symbol = symChar;
                                choices[choiceCount].label = lab;
                                choices[choiceCount].destChapter = -1;
                                choiceCount++;
                            }
                        } else {
                            choices[choiceCount].symbol = symChar;
                            choices[choiceCount].label = lab;
                            choices[choiceCount].destChapter = -1;
                            choiceCount++;
                        }
                        continue;
                    }
                }
            }
            char *lineWithNL;
            asprintf(&lineWithNL, "%s\n", ln);
            textBuf = append_line(textBuf, &textLen, &textCap, lineWithNL);
            free(lineWithNL);
        }
        current->text = textBuf ? textBuf : strdup("");
        current->choices = choices;
        current->choiceCount = choiceCount;
        current->infos = infos;
        current->infoCount = infoCount;
        current->endingAct = endingAct;
        current->endingNumber = endingNumber;
        current->endingTotal = endingTotal;
        for (size_t li = 0; li < linesCount; ++li) {
            free(lines[li]);
        }
        free(lines);
        lines = NULL;
        linesCount = 0;
        linesCap = 0;
    }
    free(line);
    fclose(fp);
    /* Link choices to destination chapter indices by matching labels to titles */
    for (int i = 0; i < cl->count; ++i) {
        Chapter *ch = &cl->chapters[i];
        for (int c = 0; c < ch->choiceCount; ++c) {
            Choice *choice = &ch->choices[c];
            /* Match choice label (case insensitive) to chapter titles */
            char *labelTrim = trim(choice->label);
            /* Convert label to uppercase copy for comparison */
            char *labUp = strdup(labelTrim);
            strtoupper(labUp);
            int dest = -1;
            for (int j = 0; j < cl->count; ++j) {
                char *titleUp = strdup(cl->chapters[j].title);
                strtoupper(titleUp);
                if (strcmp(titleUp, labUp) == 0) {
                    dest = j;
                    free(titleUp);
                    break;
                }
                free(titleUp);
            }
            free(labUp);
            choice->destChapter = dest;
        }
    }
    return 0;
}

/* Create the save directory if it does not already exist.  Returns 0 on
 * success or if the directory already exists; negative on error. */
static int ensure_save_dir(void) {
    struct stat st;
    if (stat(SAVE_DIR, &st) == -1) {
        if (mkdir(SAVE_DIR, 0755) == -1) {
            perror("mkdir");
            return -1;
        }
    } else if (!S_ISDIR(st.st_mode)) {
        fprintf(stderr, "Error: %s exists but is not a directory\n", SAVE_DIR);
        return -1;
    }
    return 0;
}

/* List existing saves by scanning the save directory for files ending
 * with "_narration.txt".  Returns an array of strings (save names without
 * suffixes) and the count via out parameter.  Caller must free the array
 * and each string. */
static char **list_saves(int *outCount) {
    *outCount = 0;
    DIR *dir = opendir(SAVE_DIR);
    if (!dir) return NULL;
    struct dirent *entry;
    char **names = NULL;
    int count = 0;
    int cap = 0;
    while ((entry = readdir(dir)) != NULL) {
        /* We only consider files that end with "_narration.txt" */
        const char *fname = entry->d_name;
        size_t len = strlen(fname);
        const char *suffix = "_narration.txt";
        size_t suffLen = strlen(suffix);
        if (len > suffLen && strcmp(fname + (len - suffLen), suffix) == 0) {
            /* Extract save name (remove suffix) */
            size_t baseLen = len - suffLen;
            char *base = (char *)malloc(baseLen + 1);
            strncpy(base, fname, baseLen);
            base[baseLen] = '\0';
            /* Add to list */
            if (count >= cap) {
                int newCap = (cap == 0 ? 4 : cap * 2);
                char **tmp = (char **)realloc(names, newCap * sizeof(char *));
                if (!tmp) {
                    free(base);
                    continue;
                }
                names = tmp;
                cap = newCap;
            }
            names[count++] = base;
        }
    }
    closedir(dir);
    *outCount = count;
    return names;
}

/* Write a line to a file (appending).  Creates the file if it doesn’t exist. */
static void append_line_to_file(const char *filepath, const char *line) {
    FILE *fp = fopen(filepath, "a");
    if (!fp) return;
    fputs(line, fp);
    fclose(fp);
}

/* Load global endings file into memory.  The file contains lines of the form
 * "Act I: 1,2" where the numbers are endings reached.  Returns a newly
 * allocated copy of the file contents or NULL if not present.  Caller must
 * free. */
static char *read_file_contents(const char *path) {
    FILE *fp = fopen(path, "r");
    if (!fp) return NULL;
    fseek(fp, 0, SEEK_END);
    long len = ftell(fp);
    if (len < 0) {
        fclose(fp);
        return NULL;
    }
    fseek(fp, 0, SEEK_SET);
    char *data = (char *)malloc((size_t)len + 1);
    if (!data) {
        fclose(fp);
        return NULL;
    }
    size_t readLen = fread(data, 1, (size_t)len, fp);
    data[readLen] = '\0';
    fclose(fp);
    return data;
}

/* Update the global endings file with a new ending reached.  actRoman
 * indicates the act (e.g. "I", "II"); endNum is the ending number. */
static void update_global_endings(const char *actRoman, int endNum) {
    /* Read existing file */
    char *content = read_file_contents(GLOBAL_ENDINGS_FILE);
    /* Build a dictionary in memory: act -> list of endings */
    typedef struct { char *act; int *nums; int count; int cap; } ActList;
    ActList *acts = NULL;
    int actCount = 0;
    int actCap = 0;
    if (content) {
        char *line = strtok(content, "\n");
        while (line) {
            char *colon = strchr(line, ':');
            if (colon) {
                *colon = '\0';
                char *actName = trim(line);
                char *numsStr = colon + 1;
                char *numTok = strtok(numsStr, ",");
                ActList al;
                al.act = strdup(actName);
                al.nums = NULL;
                al.count = 0;
                al.cap = 0;
                while (numTok) {
                    int n = atoi(trim(numTok));
                    if (n > 0) {
                        if (al.count >= al.cap) {
                            int newCap = (al.cap == 0 ? 4 : al.cap * 2);
                            int *tmp = (int *)realloc(al.nums, newCap * sizeof(int));
                            if (tmp) {
                                al.nums = tmp;
                                al.cap = newCap;
                            }
                        }
                        if (al.nums) {
                            al.nums[al.count++] = n;
                        }
                    }
                    numTok = strtok(NULL, ",");
                }
                /* Add to acts list */
                if (actCount >= actCap) {
                    int newCap = (actCap == 0 ? 4 : actCap * 2);
                    ActList *tmpActs = (ActList *)realloc(acts, newCap * sizeof(ActList));
                    if (tmpActs) {
                        acts = tmpActs;
                        actCap = newCap;
                    }
                }
                if (acts) {
                    acts[actCount++] = al;
                }
            }
            line = strtok(NULL, "\n");
        }
        free(content);
    }
    /* Check if act exists */
    int foundAct = 0;
    for (int i = 0; i < actCount; ++i) {
        if (strcmp(acts[i].act, actRoman) == 0) {
            /* Act found */
            foundAct = 1;
            /* Check if ending already present */
            int exists = 0;
            for (int j = 0; j < acts[i].count; ++j) {
                if (acts[i].nums[j] == endNum) {
                    exists = 1;
                    break;
                }
            }
            if (!exists) {
                if (acts[i].count >= acts[i].cap) {
                    int newCap = (acts[i].cap == 0 ? 4 : acts[i].cap * 2);
                    int *tmp = (int *)realloc(acts[i].nums, newCap * sizeof(int));
                    if (tmp) {
                        acts[i].nums = tmp;
                        acts[i].cap = newCap;
                    }
                }
                acts[i].nums[acts[i].count++] = endNum;
            }
            break;
        }
    }
    if (!foundAct) {
        /* Add new act entry */
        if (actCount >= actCap) {
            int newCap = (actCap == 0 ? 4 : actCap * 2);
            ActList *tmpActs = (ActList *)realloc(acts, newCap * sizeof(ActList));
            if (tmpActs) {
                acts = tmpActs;
                actCap = newCap;
            }
        }
        if (acts) {
            ActList newAct;
            newAct.act = strdup(actRoman);
            newAct.nums = (int *)malloc(sizeof(int));
            if (newAct.nums) {
                newAct.nums[0] = endNum;
                newAct.count = 1;
                newAct.cap = 1;
                acts[actCount++] = newAct;
            }
        }
    }
    /* Write back to file */
    FILE *fp = fopen(GLOBAL_ENDINGS_FILE, "w");
    if (fp) {
        for (int i = 0; i < actCount; ++i) {
            fprintf(fp, "%s:", acts[i].act);
            for (int j = 0; j < acts[i].count; ++j) {
                fprintf(fp, "%s%d", (j == 0 ? " " : ", "), acts[i].nums[j]);
            }
            fprintf(fp, "\n");
        }
        fclose(fp);
    }
    /* Free memory */
    for (int i = 0; i < actCount; ++i) {
        free(acts[i].act);
        free(acts[i].nums);
    }
    free(acts);
}

/* Append narrative and encounters information to save files.  The save name
 * corresponds to files: <SAVE_DIR>/<name>_narration.txt and
 * <SAVE_DIR>/<name>_relations.txt.  The player name and current chapter
 * number are stored at the beginning of the narration file if it is newly
 * created.  Each call writes the current chapter title and selected choice
 * (if any).  Relationship updates are derived from the chapter’s info lines. */
static void log_progress(const char *saveName, const char *playerName, Chapter *chapter, const char *choiceLabel) {
    char narrationPath[512];
    char relationsPath[512];
    snprintf(narrationPath, sizeof(narrationPath), "%s/%s_narration.txt", SAVE_DIR, saveName);
    snprintf(relationsPath, sizeof(relationsPath), "%s/%s_relations.txt", SAVE_DIR, saveName);
    /* Check if narration file exists; if not, write header */
    FILE *nf = fopen(narrationPath, "r");
    int narrationExists = nf != NULL;
    if (nf) fclose(nf);
    nf = fopen(relationsPath, "r");
    int relationsExists = nf != NULL;
    if (nf) fclose(nf);
    /* If not exist, create and write header */
    if (!narrationExists) {
        nf = fopen(narrationPath, "w");
        if (nf) {
            fprintf(nf, "playerName=%s\n", playerName);
            fprintf(nf, "currentChapter=%d\n", chapter->number);
            fclose(nf);
        }
    }
    if (!relationsExists) {
        nf = fopen(relationsPath, "w");
        if (nf) {
            fprintf(nf, "playerName=%s\n", playerName);
            fprintf(nf, "currentChapter=%d\n", chapter->number);
            fclose(nf);
        }
    }
    /* Append narrative log */
    char buffer[2048];
    if (choiceLabel) {
        snprintf(buffer, sizeof(buffer), "Chapter %d (%s) -> Choice: %s\n", chapter->number, chapter->title, choiceLabel);
    } else {
        snprintf(buffer, sizeof(buffer), "Chapter %d (%s)\n", chapter->number, chapter->title);
    }
    append_line_to_file(narrationPath, buffer);
    /* Append relationship info */
    for (int i = 0; i < chapter->infoCount; ++i) {
        char *info = chapter->infos[i];
        /* Only log relationship lines that look like NAME: STATUS */
        char *colon = strchr(info, ':');
        if (colon) {
            int valid = 1;
            for (char *c = info; c < colon; ++c) {
                if (!isupper((unsigned char)*c) && *c != ' ' && *c != '-') {
                    valid = 0;
                    break;
                }
            }
            if (valid) {
                append_line_to_file(relationsPath, info);
            }
        }
    }
}

/* Display a coloured banner header. */
static void print_banner(void) {
    printf(ANSI_CYAN ANSI_BOLD);
    printf("\n===============================================\n");
    printf("        Detroit: The Accomplice (CYOA)         \n");
    printf("===============================================\n" ANSI_RESET);
}

/* Display the main menu and get the user's choice.  Returns a newly
 * allocated string containing the chosen save name or NULL if the user
 * chooses to exit.  Also fills playerName if creating a new save. */
static char *main_menu(char **playerNameOut) {
    int saveCount = 0;
    char **saves = list_saves(&saveCount);
    printf("\n" ANSI_GREEN "Available saves:" ANSI_RESET "\n");
    for (int i = 0; i < saveCount; ++i) {
        printf("  %d) %s\n", i + 1, saves[i]);
    }
    printf("  %d) %s\n", saveCount + 1, "Create a new save");
    printf("  0) Quit\n");
    printf("\nEnter your choice: ");
    int choice = -1;
    char input[64];
    fgets(input, sizeof(input), stdin);
    choice = atoi(input);
    char *selectedSave = NULL;
    char *playerName = NULL;
    if (choice == 0) {
        /* Quit */
    } else if (choice >= 1 && choice <= saveCount) {
        selectedSave = strdup(saves[choice - 1]);
        /* Load playerName from narration file */
        char path[512];
        snprintf(path, sizeof(path), "%s/%s_narration.txt", SAVE_DIR, selectedSave);
        FILE *fp = fopen(path, "r");
        if (fp) {
            char line[256];
            while (fgets(line, sizeof(line), fp)) {
                if (strncmp(line, "playerName=", 11) == 0) {
                    line[strcspn(line, "\n\r")] = 0;
                    playerName = strdup(line + 11);
                    break;
                }
            }
            fclose(fp);
        }
    } else if (choice == saveCount + 1) {
        /* Create new save */
        char name[256];
        printf("Enter a name for your save (no spaces): ");
        fgets(name, sizeof(name), stdin);
        name[strcspn(name, "\n\r")] = 0;
        if (strlen(name) == 0) {
            selectedSave = NULL;
        } else {
            selectedSave = strdup(name);
        }
        /* Use the default player name YN600; the story will prompt for replacement later */
        playerName = strdup("YN600");
    } else {
        printf("Invalid selection.\n");
    }
    for (int i = 0; i < saveCount; ++i) {
        free(saves[i]);
    }
    free(saves);
    *playerNameOut = playerName;
    return selectedSave;
}

/* Get current chapter index from save if exists; otherwise return 0 (first chapter). */
static int load_save_progress(const char *saveName) {
    char path[512];
    snprintf(path, sizeof(path), "%s/%s_narration.txt", SAVE_DIR, saveName);
    FILE *fp = fopen(path, "r");
    if (!fp) return 0;
    char line[256];
    int chapterNum = 0;
    while (fgets(line, sizeof(line), fp)) {
        if (strncmp(line, "currentChapter=", 15) == 0) {
            chapterNum = atoi(line + 15);
            break;
        }
    }
    fclose(fp);
    return chapterNum;
}

/* Update the current chapter number in the save file header. */
static void update_save_current_chapter(const char *saveName, int chapterNum) {
    char path[512];
    snprintf(path, sizeof(path), "%s/%s_narration.txt", SAVE_DIR, saveName);
    /* Read entire file */
    char *content = read_file_contents(path);
    FILE *fp = fopen(path, "w");
    if (!fp) {
        free(content);
        return;
    }
    if (content) {
        char *line = strtok(content, "\n");
        int wroteCurrent = 0;
        while (line) {
            if (strncmp(line, "currentChapter=", 15) == 0) {
                fprintf(fp, "currentChapter=%d\n", chapterNum);
                wroteCurrent = 1;
            } else {
                fprintf(fp, "%s\n", line);
            }
            line = strtok(NULL, "\n");
        }
        if (!wroteCurrent) {
            fprintf(fp, "currentChapter=%d\n", chapterNum);
        }
        free(content);
    } else {
        fprintf(fp, "playerName=YN600\n");
        fprintf(fp, "currentChapter=%d\n", chapterNum);
    }
    fclose(fp);
}

/* Update the stored playerName in both narration and relations files.  This
 * function searches for lines starting with "playerName=" and replaces the
 * value with the new name.  If the header is not present, it inserts it
 * at the top of the file. */
/* Helper to update the playerName in a single save file */
static void update_file_playerName(const char *path, const char *playerName) {
    char *content = read_file_contents(path);
    FILE *fp = fopen(path, "w");
    if (!fp) {
        free(content);
        return;
    }
    if (content) {
        char *token = strtok(content, "\n");
        int wroteName = 0;
        while (token) {
            if (strncmp(token, "playerName=", 11) == 0) {
                fprintf(fp, "playerName=%s\n", playerName);
                wroteName = 1;
            } else {
                fprintf(fp, "%s\n", token);
            }
            token = strtok(NULL, "\n");
        }
        if (!wroteName) {
            fprintf(fp, "playerName=%s\n", playerName);
        }
        free(content);
    } else {
        fprintf(fp, "playerName=%s\n", playerName);
    }
    fclose(fp);
}

static void update_save_player_name(const char *saveName, const char *playerName) {
    char narrationPath[512];
    char relationsPath[512];
    snprintf(narrationPath, sizeof(narrationPath), "%s/%s_narration.txt", SAVE_DIR, saveName);
    snprintf(relationsPath, sizeof(relationsPath), "%s/%s_relations.txt", SAVE_DIR, saveName);
    update_file_playerName(narrationPath, playerName);
    update_file_playerName(relationsPath, playerName);
}

/* Main game loop: run the interactive adventure. */
static void run_game(ChapterList *cl, const char *saveName, char *playerName) {
    /* Determine starting chapter based on save */
    int startChapterNum = load_save_progress(saveName);
    int currentIndex = 0;
    /* Find chapter with matching number */
    for (int i = 0; i < cl->count; ++i) {
        if (cl->chapters[i].number == startChapterNum) {
            currentIndex = i;
            break;
        }
    }
    while (1) {
        Chapter *ch = &cl->chapters[currentIndex];
        /* Clear screen (optional) */
        printf("\033[2J\033[H");
        print_banner();
        /* No special pre‑prompting here – name replacement is handled when the corresponding choice is selected */
        /* Print chapter title */
        printf(ANSI_BOLD ANSI_YELLOW "\nChapter %d: %s\n" ANSI_RESET, ch->number, ch->title);
        printf("\n");
        /* Replace YN600 with playerName in text */
        char *displayText = replace_substr(ch->text, "YN600", playerName);
        printf("%s\n", displayText);
        free(displayText);
        /* Print relationship/info updates from previous chapter (if any) */
        if (ch->infoCount > 0) {
            printf(ANSI_CYAN "-- Info --\n" ANSI_RESET);
            for (int i = 0; i < ch->infoCount; ++i) {
                char *info = ch->infos[i];
                /* Colour act completion lines */
                if (strncmp(info, "ACT ", 4) == 0) {
                    printf(ANSI_MAGENTA "%s\n" ANSI_RESET, info);
                } else if (strncasecmp(info, "ENDING", 6) == 0) {
                    printf(ANSI_RED "%s\n" ANSI_RESET, info);
                } else {
                    printf(ANSI_GREEN "%s\n" ANSI_RESET, info);
                }
            }
            printf("\n");
        }
        /* Check if this chapter marks an ending and update global file */
        if (ch->endingAct && ch->endingNumber > 0 && ch->endingTotal > 0) {
            update_global_endings(ch->endingAct, ch->endingNumber);
        }
        /* Log progress without a selected choice yet */
        log_progress(saveName, playerName, ch, NULL);
        /* If no choices, the story ends */
        if (ch->choiceCount == 0) {
            printf(ANSI_RED "\nNo further choices. The story ends here.\n" ANSI_RESET);
            break;
        }
        /* Present choices */
        printf(ANSI_BOLD "Available choices:" ANSI_RESET "\n");
        /* Build mapping from display index to actual choice index */
        int mappingCount = 0;
        int *mapping = (int *)malloc(sizeof(int) * ch->choiceCount);
        for (int i = 0; i < ch->choiceCount; ++i) {
            mapping[mappingCount++] = i;
            Choice *choice = &ch->choices[i];
            /* Colour by symbol */
            const char *colour;
            if (choice->symbol == 'O' || choice->symbol == 'o') {
                colour = ANSI_GREEN;
            } else if (choice->symbol == 'X' || choice->symbol == 'x') {
                colour = ANSI_RED;
            } else {
                colour = ANSI_YELLOW;
            }
            printf("  %d) %s%s%s\n", mappingCount, colour, choice->label, ANSI_RESET);
        }
        printf("  0) Save & Exit\n");
        printf("\nEnter your choice: ");
        char buf[64];
        if (!fgets(buf, sizeof(buf), stdin)) {
            free(mapping);
            break;
        }
        int opt = atoi(buf);
        if (opt == 0) {
            /* Update current chapter in save header */
            update_save_current_chapter(saveName, ch->number);
            printf("Progress saved. Goodbye!\n");
            free(mapping);
            break;
        } else if (opt >= 1 && opt <= mappingCount) {
            int actualIdx = mapping[opt - 1];
            Choice *sel = &ch->choices[actualIdx];
            /* Log chosen option */
            log_progress(saveName, playerName, ch, sel->label);
            /* Determine if this is a name replacement or do‑nothing choice */
            char *lab = trim(sel->label);
            char labUp[256];
            snprintf(labUp, sizeof(labUp), "%s", lab);
            strtoupper(labUp);
            int replaceIndex = -1;
            int doNothingIndex = -1;
            /* Find indices of REPLACE and DO NOTHING choices */
            for (int i = 0; i < ch->choiceCount; ++i) {
                char *clab = trim(ch->choices[i].label);
                char cUp[256];
                snprintf(cUp, sizeof(cUp), "%s", clab);
                strtoupper(cUp);
                if (strcmp(cUp, "REPLACE") == 0 || strcmp(cUp, "REPLACE YN600") == 0) {
                    replaceIndex = i;
                } else if (strcmp(cUp, "DO NOTHING") == 0) {
                    doNothingIndex = i;
                }
            }
            /* Flag to indicate we should stay in the same chapter after handling */
            int stayHere = 0;
            if ((strcmp(labUp, "REPLACE") == 0 || strcmp(labUp, "REPLACE YN600") == 0) && replaceIndex >= 0) {
                /* Ask for new name */
                char newName[256];
                printf("Entrez le nouveau nom: ");
                if (fgets(newName, sizeof(newName), stdin)) {
                    newName[strcspn(newName, "\n\r")] = '\0';
                    if (strlen(newName) > 0) {
                        free(playerName);
                        playerName = strdup(newName);
                        update_save_player_name(saveName, playerName);
                    }
                }
                stayHere = 1;
            } else if (strcmp(labUp, "DO NOTHING") == 0 && doNothingIndex >= 0) {
                /* Keep default name */
                stayHere = 1;
            }
            if (stayHere && replaceIndex >= 0 && doNothingIndex >= 0) {
                /* Remove both REPLACE and DO NOTHING choices from this chapter */
                /* Free their labels */
                free(ch->choices[replaceIndex].label);
                free(ch->choices[doNothingIndex].label);
                /* Remove the higher index first */
                int idx1 = replaceIndex;
                int idx2 = doNothingIndex;
                if (idx1 < idx2) {
                    int temp = idx1;
                    idx1 = idx2;
                    idx2 = temp;
                }
                /* Remove idx1 */
                for (int j = idx1; j < ch->choiceCount - 1; ++j) {
                    ch->choices[j] = ch->choices[j + 1];
                }
                ch->choiceCount--;
                /* Now remove idx2 */
                for (int j = idx2; j < ch->choiceCount - 1; ++j) {
                    ch->choices[j] = ch->choices[j + 1];
                }
                ch->choiceCount--;
                /* Après la suppression, couper le texte avant READY */
                char *readyPtr = strstr(ch->text, "READY");
                if (readyPtr) {
                    char *postPtr = strchr(readyPtr, '\n');
                    if (postPtr) postPtr++; else postPtr = readyPtr;
                    char *newText = strdup(postPtr);
                    if (newText) {
                        free(ch->text);
                        ch->text = newText;
                    }
                }
                free(mapping);
                continue; /* Revenir au début de la boucle pour afficher la suite du chapitre */
            }
            /* Normal branch: follow destination */
            if (sel->destChapter >= 0 && sel->destChapter < cl->count) {
                currentIndex = sel->destChapter;
                update_save_current_chapter(saveName, cl->chapters[currentIndex].number);
                free(mapping);
                continue;
            } else {
                printf(ANSI_RED "Destination chapter not found.\n" ANSI_RESET);
                free(mapping);
                break;
            }
        } else {
            printf(ANSI_RED "Invalid choice.\n" ANSI_RESET);
        }
        free(mapping);
    }
}

int main(void) {
    /* Ensure the save directory exists */
    if (ensure_save_dir() != 0) {
        return 1;
    }
    /* Parse story into chapters */
    ChapterList cl;
    init_chapter_list(&cl);
    if (parse_story(&cl, 0) != 0) {
        fprintf(stderr, "Failed to parse story file.\n");
        free_chapter_list(&cl);
        return 1;
    }
    /* Main loop: choose save slot or create new */
    while (1) {
        print_banner();
        char *playerName = NULL;
        char *saveName = main_menu(&playerName);
        if (!saveName) {
            /* Exit */
            free(playerName);
            break;
        }
        if (!playerName) {
            /* This means existing save loaded but no playerName found */
            playerName = strdup("YN600");
        }
        /* Run interactive game */
        run_game(&cl, saveName, playerName);
        free(saveName);
        free(playerName);
    }
    free_chapter_list(&cl);
    return 0;
}