/*
 * Detroit: The Accomplice – Interactive Story Engine
 *
 * This program implements a simple choose‑your‑own‑adventure player for
 * the interactive fanfic "Detroit: The Accomplice".  The story data is
 * loaded from a separate plain‑text file (`game_data.txt`) generated by
 * `parse_story.py`.  Each page contains a title, a block of narrative
 * text and a list of choices.  Choices link to other pages via the
 * title of the target chapter.  The program provides two modes of
 * interaction simultaneously:
 *
 * • Console: The full narrative text is printed to standard output on
 * a black background/white foreground console.  This satisfies the
 * requirement for readability in an "invite de commande".
 *
 * • Graphical window (SDL2): A window displays the current page
 * title and presents each choice as a clickable button.  The
 * player interacts with the story using the mouse.  A key press
 * ('r') shows the relationship log in the console at any time.
 *
 * Game state is persisted: every time you start the program it creates
 * a new session log (`session_YYYYMMDD_HHMMSS.txt`) containing the
 * sequence of pages you visited.  Additionally, a global
 * relationships log (`relations.txt`) is appended with each page
 * title you visit.  You can review the relationships log during a
 * session by pressing the 'r' key while the SDL window is focused.
 *
 * NOTE: To build this program you need the SDL2 and SDL2_ttf
 * libraries installed on your system.  On Debian/Ubuntu you can
 * install them with:
 *
 * sudo apt install libsdl2-dev libsdl2-ttf-dev
 *
 * Compile with:
 *
 * gcc main.c -o story_game -lSDL2 -lSDL2_ttf
 *
 * The program expects `game_data.txt` in the working directory.
 */

#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/stat.h>
#include <dirent.h>

/* Maximum number of choices per page.  Adjust if the story uses more. */
#define MAX_CHOICES 16
/* Screen dimensions */
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
/* Font size for rendering text in the SDL window */
#define FONT_SIZE 20

typedef struct {
    char *text;      /* Text shown for this choice */
    char *target;    /* Title of the target page */
    int target_index;/* Index of the target page, resolved after loading */
    SDL_Rect rect;   /* Rectangle bounding the choice button in the window */
} Choice;

typedef struct {
    char *title;
    char *text;
    int num_choices;
    Choice *choices;
} Page;

/* Global array of pages and its length. */
static Page *pages = NULL;
static int page_count = 0;

/* Forward declarations */
static void free_pages(void);
static int load_game_data(const char *filename);
static int find_page_index(const char *title);
static void render_text_center(SDL_Renderer *renderer, TTF_Font *font,
                               const char *text, int y, SDL_Color color);

/* Helper: trim leading and trailing whitespace in place. */
static char *trim_whitespace(char *str) {
    if (!str) return str;
    /* Trim leading spaces */
    while (*str && (*str == ' ' || *str == '\t')) {
        str++;
    }
    /* Trim trailing spaces */
    char *end = str + strlen(str);
    while (end > str && (end[-1] == ' ' || end[-1] == '\t' || end[-1] == '\n' || end[-1] == '\r')) {
        end--;
    }
    *end = '\0';
    return str;
}

/* Fonction pour nettoyer le texte de ses balises indésirables comme <source...> (modifie la chaîne sur place) */
static void nettoyer_balises(char* texte) {
    if (!texte) return;
    
    char* src = texte;
    char* dst = texte;
    int in_tag = 0;
    
    while (*src != '\0') {
        // Détection du début d'une balise
        if (*src == '<') {
            in_tag = 1;
            src++;
            continue;
        }
        
        // Si on est à l'intérieur d'une balise, on ignore les caractères jusqu'à '>'
        if (in_tag) {
            if (*src == '>') {
                in_tag = 0;
                src++;
                // Sauter l'espace qui suit généralement la balise fermante s'il y en a un
                if (*src == ' ') src++;
            } else {
                src++;
            }
            continue;
        }
        
        // Copier les caractères normaux
        *dst++ = *src++;
    }
    *dst = '\0'; // Nouvelle fin de chaîne propre
}

// Fonction pour lire tout le contenu d'un fichier texte dans une chaîne (buffer)
char* lire_chapitre(const char* nom_fichier) {
    char chemin[256];
    snprintf(chemin, sizeof(chemin), "chapitres/%s", nom_fichier); // Construit le chemin
    
    FILE* file = fopen(chemin, "r");
    if (!file) {
        printf("Erreur: Impossible d'ouvrir le fichier %s\n", chemin);
        return NULL;
    }
    
    // Obtenir la taille du fichier
    fseek(file, 0, SEEK_END);
    long length = ftell(file);
    fseek(file, 0, SEEK_SET);
    
    char* buffer = malloc(length + 1);
    if (buffer) {
        fread(buffer, 1, length, file);
        buffer[length] = '\0'; // Fin de chaîne
    }
    fclose(file);
    return buffer;
}

/* Load chapters from a directory of individual chapter files. */
static int load_chapters_dir(const char *dir_path) {
    DIR *dir = opendir(dir_path);
    if (!dir) {
        fprintf(stderr, "Could not open directory %s: %s\n", dir_path, strerror(errno));
    return -1;
}
    struct dirent *entry;
    /* We'll store file names first so we can sort them for consistent order */
    char **filenames = NULL;
    size_t count = 0;
    while ((entry = readdir(dir)) != NULL) {
        /* Skip non-regular files and hidden files */
        #ifdef DT_REG
        if (entry->d_type != DT_REG && entry->d_type != DT_UNKNOWN) {
            continue;
        }
        #endif
        const char *name = entry->d_name;
        /* Skip dot files */
        if (name[0] == '.') continue;
        /* Only consider .txt files */
        const char *dot = strrchr(name, '.');
        if (!dot || strcmp(dot, ".txt") != 0) {
            continue;
        }
        /* Save the file name */
        filenames = realloc(filenames, sizeof(char*) * (count + 1));
        filenames[count] = strdup(name);
        count++;
    }
    closedir(dir);
    if (count == 0) {
        free(filenames);
        fprintf(stderr, "No chapter files found in %s\n", dir_path);
        return -1;
    }
    /* Sort filenames alphabetically to ensure deterministic ordering */
    for (size_t i = 0; i < count; i++) {
        for (size_t j = i + 1; j < count; j++) {
            if (strcmp(filenames[i], filenames[j]) > 0) {
                char *tmp = filenames[i];
                filenames[i] = filenames[j];
                filenames[j] = tmp;
            }
        }
    }
    /* Free any previously loaded pages */
    free_pages();
    pages = NULL;
    page_count = 0;

    /* Iterate over sorted files and parse each */
    for (size_t i = 0; i < count; i++) {
        // Utilisation de lire_chapitre au lieu de fopen/getline
        char *file_content = lire_chapitre(filenames[i]);
        if (!file_content) {
            continue;
        }
        
        Page current = {0};
        /* We will build the text buffer dynamically */
        char *text_buffer = NULL;
        size_t text_buf_size = 0;
        size_t text_len = 0;
        int in_text = 0;
        int in_choices = 0;
        
        char *ptr = file_content;
        while (*ptr) {
            char *line = ptr;
            
            // Find the end of the current line
            while (*ptr && *ptr != '\n') {
                ptr++;
            }
            int has_newline = (*ptr == '\n');
            if (has_newline) {
                *ptr = '\0'; // Replace newline with null terminator temporarily
            }
            
            size_t read = strlen(line);
            
            /* Trim carriage return */
            while (read > 0 && line[read - 1] == '\r') {
                line[--read] = '\0';
            }
            
            /* Skip empty lines outside of text accumulation */
            if (read == 0) {
                if (has_newline) ptr++;
                continue;
            }
            if (strncmp(line, "Title:", 6) == 0) {
                char *p = line + 6;
                p = trim_whitespace(p);
                current.title = strdup(p);
            }
            else if (strcmp(line, "Text:") == 0) {
                in_text = 1;
                in_choices = 0;
            }
            else if (strcmp(line, "Choices:") == 0) {
                in_choices = 1;
                in_text = 0;
                current.num_choices = 0;
                current.choices = NULL;
            }
            else if (in_text) {
                /* Append line to text buffer with newline */
                size_t needed = text_len + read + 2;
                if (needed > text_buf_size) {
                    size_t new_size = text_buf_size ? text_buf_size * 2 : 1024;
                    while (new_size < needed) new_size *= 2;
                    text_buffer = realloc(text_buffer, new_size);
                    text_buf_size = new_size;
                }
                memcpy(text_buffer + text_len, line, read);
                text_len += read;
                text_buffer[text_len++] = '\n';
                text_buffer[text_len] = '\0';
            }
            else if (in_choices) {
                /* Expect format: - <choice text> -> <target title> (id: ...)? */
                if (strncmp(line, "- ", 2) == 0) {
                    char *p = line + 2;
                    char *arrow = strstr(p, "->");
                    if (arrow) {
                        *arrow = '\0';
                        char *choice_text = trim_whitespace(p);
                        char *target = trim_whitespace(arrow + 2);
                        /* If there's a parenthesis, strip it and anything after */
                        char *paren = strchr(target, '(');
                        if (paren) {
                            *paren = '\0';
                        }
                        /* Duplicate strings */
                        char *opt_text = strdup(choice_text);
                        char *target_title = strdup(target);
                        current.choices = realloc(current.choices, sizeof(Choice) * (current.num_choices + 1));
                        current.choices[current.num_choices].text = opt_text;
                        current.choices[current.num_choices].target = target_title;
                        current.choices[current.num_choices].target_index = -1;
                        current.num_choices++;
                    }
                }
            }
            
            // Advance ptr past the newline to read the next line
            if (has_newline) {
                ptr++;
            }
        }
        
        // Libérer le buffer alloué par lire_chapitre
        free(file_content);
        
        /* Finalise text */
        current.text = text_buffer ? text_buffer : strdup("");
        
        // ========================================================
        // NOUVEAU : On nettoie les balises du texte de narration !
        // ========================================================
        nettoyer_balises(current.text);
        
        /* Add to pages array */
        pages = realloc(pages, sizeof(Page) * (page_count + 1));
        pages[page_count++] = current;
        free(filenames[i]);
    }
    free(filenames);
    return 0;
}

int main(int argc, char *argv[]) {
    (void)argc;
    (void)argv;

    /* Load story data.  Prefer individual chapter files in the 'chapitres' directory.
     * If the directory does not exist or fails to load, fall back to game_data.txt. */
    struct stat st;
    int load_result = -1;
    if (stat("chapitres", &st) == 0 && S_ISDIR(st.st_mode)) {
        load_result = load_chapters_dir("chapitres");
    }
    if (load_result != 0) {
        load_result = load_game_data("game_data.txt");
    }
    if (load_result != 0) {
        fprintf(stderr, "Failed to load story data.\n");
        return EXIT_FAILURE;
    }

    /* Resolve target indices */
    for (int i = 0; i < page_count; i++) {
        Page *p = &pages[i];
        for (int j = 0; j < p->num_choices; j++) {
            int idx = find_page_index(p->choices[j].target);
            p->choices[j].target_index = idx;
        }
    }

    /* Initialise SDL and SDL_ttf */
    if (SDL_Init(SDL_INIT_VIDEO) != 0) {
        fprintf(stderr, "SDL_Init Error: %s\n", SDL_GetError());
        free_pages();
        return EXIT_FAILURE;
    }
    if (TTF_Init() == -1) {
        fprintf(stderr, "TTF_Init Error: %s\n", TTF_GetError());
        SDL_Quit();
        free_pages();
        return EXIT_FAILURE;
    }

    /*
     * Load a font for rendering.  Fonts may reside in different
     * directories on different systems.  The program will try to
     * locate a usable TrueType font automatically.  If the first
     * command line argument is present, it will be interpreted as
     * the font path and tried first.  Otherwise a list of common
     * locations is checked.  You may also place a .ttf file in the
     * current directory (e.g. DejaVuSans.ttf or FreeSans.ttf) and it
     * will be found.
     */
    const char *font_candidates[] = {
        NULL,            /* optional user‑supplied path (argv[1]) */
        "./courrier.ttf", /* default font in local directory */
        NULL
    };
    if (argc > 1) {
        font_candidates[0] = argv[1];
    }
    TTF_Font *font = NULL;
    const char *used_font_path = NULL;
    for (int i = 0; font_candidates[i] != NULL; i++) {
        const char *path = font_candidates[i];
        if (!path || !*path) {
            continue;
        }
        font = TTF_OpenFont(path, FONT_SIZE);
        if (font) {
            used_font_path = path;
            break;
        } else {
            /* Log the error for each font candidate to aid debugging */
            fprintf(stderr, "Impossible d\'ouvrir la police %s : %s\n", path, TTF_GetError());
        }
    }
    if (!font) {
        fprintf(stderr,
                "Échec du chargement de la police. Assurez-vous que 'courrier.ttf' se trouve dans le répertoire du programme,\n"
                "ou passez le chemin d'un fichier .ttf valide en argument.\n");
        TTF_Quit();
        SDL_Quit();
        free_pages();
        return EXIT_FAILURE;
    } else {
        fprintf(stderr, "Utilisation de la police : %s\n", used_font_path);
    }

    /* Create SDL window and renderer */
    SDL_Window *window = SDL_CreateWindow(
        "Detroit: The Accomplice", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        SCREEN_WIDTH, SCREEN_HEIGHT, SDL_WINDOW_SHOWN);
    if (!window) {
        fprintf(stderr, "SDL_CreateWindow Error: %s\n", SDL_GetError());
        TTF_CloseFont(font);
        TTF_Quit();
        SDL_Quit();
        free_pages();
        return EXIT_FAILURE;
    }
    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1,
                                                SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    if (!renderer) {
        fprintf(stderr, "SDL_CreateRenderer Error: %s\n", SDL_GetError());
        SDL_DestroyWindow(window);
        TTF_CloseFont(font);
        TTF_Quit();
        SDL_Quit();
        free_pages();
        return EXIT_FAILURE;
    }

    /* Prepare session log file */
    time_t t = time(NULL);
    struct tm *tm_info = localtime(&t);
    char session_filename[64];
    strftime(session_filename, sizeof(session_filename), "session_%Y%m%d_%H%M%S.txt", tm_info);
    FILE *session_file = fopen(session_filename, "w");
    if (!session_file) {
        fprintf(stderr, "Failed to create session log: %s\n", strerror(errno));
        SDL_DestroyRenderer(renderer);
        SDL_DestroyWindow(window);
        TTF_CloseFont(font);
        TTF_Quit();
        SDL_Quit();
        free_pages();
        return EXIT_FAILURE;
    }
    /* Open or create the relationships log.  Append mode retains history. */
    FILE *relations_file = fopen("relations.txt", "a+");
    if (!relations_file) {
        fprintf(stderr, "Failed to open relations log: %s\n", strerror(errno));
        fclose(session_file);
        SDL_DestroyRenderer(renderer);
        SDL_DestroyWindow(window);
        TTF_CloseFont(font);
        TTF_Quit();
        SDL_Quit();
        free_pages();
        return EXIT_FAILURE;
    }

    /* Game loop variables */
    int current_index = 0;
    int running = 1;
    while (running) {
        if (current_index < 0 || current_index >= page_count) {
            fprintf(stderr, "Invalid page index %d; exiting.\n", current_index);
            break;
        }
        Page *page = &pages[current_index];
        /* Print narrative text to console */
        printf("\n\n=== %s ===\n", page->title);
        printf("%s\n\n", page->text);
        fflush(stdout);
        /* Append to session and relations logs */
        fprintf(session_file, "%s\n", page->title);
        fprintf(relations_file, "%s\n", page->title);
        fflush(session_file);
        fflush(relations_file);

        /* Prepare rectangles for choices.  We arrange them vertically. */
        int num = page->num_choices;
        int button_height = 40;
        int button_width = SCREEN_WIDTH - 100;
        int start_y = 200;
        int spacing = 10;
        for (int i = 0; i < num; i++) {
            Choice *ch = &page->choices[i];
            ch->rect.x = (SCREEN_WIDTH - button_width) / 2;
            ch->rect.y = start_y + i * (button_height + spacing);
            ch->rect.w = button_width;
            ch->rect.h = button_height;
        }

        int waiting_for_choice = 1;
        while (waiting_for_choice && running) {
            SDL_Event e;
            while (SDL_PollEvent(&e)) {
                switch (e.type) {
                case SDL_QUIT:
                    running = 0;
                    waiting_for_choice = 0;
                    break;
                case SDL_MOUSEBUTTONDOWN:
                    if (e.button.button == SDL_BUTTON_LEFT) {
                        int mx = e.button.x;
                        int my = e.button.y;
                        for (int i = 0; i < num; i++) {
                            Choice *ch = &page->choices[i];
                            if (mx >= ch->rect.x && mx <= ch->rect.x + ch->rect.w &&
                                my >= ch->rect.y && my <= ch->rect.y + ch->rect.h) {
                                /* Transition to target page */
                                current_index = ch->target_index;
                                waiting_for_choice = 0;
                                break;
                            }
                        }
                    }
                    break;
                case SDL_KEYDOWN:
                    switch (e.key.keysym.sym) {
                    case SDLK_r:
                        /* Dump relationships log to console */
                        {
                            FILE *rf = fopen("relations.txt", "r");
                            if (rf) {
                                printf("\n-- Relations log --\n");
                                char line[512];
                                while (fgets(line, sizeof(line), rf)) {
                                    fputs(line, stdout);
                                }
                                printf("-- End of relations --\n\n");
                                fclose(rf);
                            }
                        }
                        break;
                    case SDLK_q:
                        /* Quit the program */
                        running = 0;
                        waiting_for_choice = 0;
                        break;
                    default:
                        break;
                    }
                    break;
                }
            }
            /* Render current page title and choices */
            SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
            SDL_RenderClear(renderer);
            /* Draw page title centered at top */
            SDL_Color title_color = {255, 255, 255, 255};
            render_text_center(renderer, font, page->title, 50, title_color);
            /* Draw each choice */
            for (int i = 0; i < num; i++) {
                Choice *ch = &page->choices[i];
                /* Draw button background */
                SDL_Color button_color = {40, 40, 40, 255};
                SDL_SetRenderDrawColor(renderer, button_color.r, button_color.g, button_color.b, button_color.a);
                SDL_RenderFillRect(renderer, &ch->rect);
                /* Draw button outline */
                SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
                SDL_RenderDrawRect(renderer, &ch->rect);
                /* Draw text centered within the button */
                render_text_center(renderer, font, ch->text, ch->rect.y + (button_height - FONT_SIZE) / 2, title_color);
            }
            SDL_RenderPresent(renderer);
        }
        /* If there are no choices (terminal page), end game */
        if (page->num_choices == 0) {
            printf("\n*** End of story. Thank you for playing! ***\n");
            running = 0;
        }
    }

    /* Cleanup */
    fclose(session_file);
    fclose(relations_file);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    TTF_CloseFont(font);
    TTF_Quit();
    SDL_Quit();
    free_pages();
    return EXIT_SUCCESS;
}

/*
 * Load the game data file into memory.  Returns 0 on success, non-zero
 * on failure.  The file format is described in parse_story.py.
 */
static int load_game_data(const char *filename) {
    FILE *fp = fopen(filename, "r");
    if (!fp) {
        fprintf(stderr, "Could not open %s: %s\n", filename, strerror(errno));
        return -1;
    }
    char *line = NULL;
    size_t len = 0;
    ssize_t read;
    Page current = {0};
    int in_text = 0;
    int in_choices = 0;
    char *text_buffer = NULL;
    size_t text_buf_size = 0;
    size_t text_len = 0;
    while ((read = getline(&line, &len, fp)) != -1) {
        /* Trim trailing newline */
        while (read > 0 && (line[read - 1] == '\n' || line[read - 1] == '\r')) {
            line[--read] = '\0';
        }
        if (strcmp(line, "---PAGE---") == 0) {
            /* If we are already constructing a page, save it */
            if (current.title) {
                current.text = text_buffer ? text_buffer : strdup("");
                /* Add current page to array */
                pages = realloc(pages, sizeof(Page) * (page_count + 1));
                pages[page_count++] = current;
                /* Reset state */
                current = (Page){0};
                text_buffer = NULL;
                text_buf_size = 0;
                text_len = 0;
            }
            continue;
        }
        if (strncmp(line, "TITLE:", 6) == 0) {
            const char *p = line + 6;
            while (*p == ' ') p++;
            current.title = strdup(p);
            continue;
        }
        if (strcmp(line, "TEXT:") == 0) {
            in_text = 1;
            continue;
        }
        if (strcmp(line, "ENDTEXT") == 0) {
            in_text = 0;
            continue;
        }
        if (strcmp(line, "CHOICES:") == 0) {
            in_choices = 1;
            current.num_choices = 0;
            current.choices = NULL;
            continue;
        }
        if (strcmp(line, "ENDCHOICES") == 0) {
            in_choices = 0;
            continue;
        }
        if (in_text) {
            /* Append line to text buffer */
            size_t needed = text_len + strlen(line) + 2; /* newline and null terminator later */
            if (needed > text_buf_size) {
                size_t new_size = text_buf_size ? text_buf_size * 2 : 1024;
                while (new_size < needed) new_size *= 2;
                text_buffer = realloc(text_buffer, new_size);
                text_buf_size = new_size;
            }
            memcpy(text_buffer + text_len, line, strlen(line));
            text_len += strlen(line);
            text_buffer[text_len++] = '\n';
            text_buffer[text_len] = '\0';
            continue;
        }
        if (in_choices) {
            /* Parse choice line: option::target */
            char *sep = strstr(line, "::");
            if (!sep) {
                continue; /* malformed line */
            }
            *sep = '\0';
            const char *opt_text = line;
            const char *target = sep + 2;
            current.choices = realloc(current.choices,
                                      sizeof(Choice) * (current.num_choices + 1));
            current.choices[current.num_choices].text = strdup(opt_text);
            current.choices[current.num_choices].target = strdup(target);
            current.choices[current.num_choices].target_index = -1;
            current.num_choices++;
            continue;
        }
    }
    /* Save the final page if present */
    if (current.title) {
        current.text = text_buffer ? text_buffer : strdup("");
        pages = realloc(pages, sizeof(Page) * (page_count + 1));
        pages[page_count++] = current;
    } else {
        free(text_buffer);
    }
    free(line);
    fclose(fp);
    return 0;
}

/* Free all allocated pages */
static void free_pages(void) {
    for (int i = 0; i < page_count; i++) {
        Page *p = &pages[i];
        free(p->title);
        free(p->text);
        for (int j = 0; j < p->num_choices; j++) {
            free(p->choices[j].text);
            free(p->choices[j].target);
        }
        free(p->choices);
    }
    free(pages);
    pages = NULL;
    page_count = 0;
}

/* Find the index of the page whose title matches the given string.  Returns
 * -1 if not found.  The match is case-sensitive. */
static int find_page_index(const char *title) {
    for (int i = 0; i < page_count; i++) {
        if (strcmp(pages[i].title, title) == 0) {
            return i;
        }
    }
    return -1;
}

/* Render a single line of text centred horizontally in the window.  The y
 * coordinate specifies the top of the text.  The caller must ensure the
 * renderer's background has been cleared and presented. */
static void render_text_center(SDL_Renderer *renderer, TTF_Font *font,
                               const char *text, int y, SDL_Color color) {
    if (!text || !*text) return;
    SDL_Surface *surface = TTF_RenderUTF8_Blended(font, text, color);
    if (!surface) {
        fprintf(stderr, "TTF_RenderUTF8_Blended error: %s\n", TTF_GetError());
        return;
    }
    SDL_Texture *texture = SDL_CreateTextureFromSurface(renderer, surface);
    if (!texture) {
        fprintf(stderr, "SDL_CreateTextureFromSurface error: %s\n", SDL_GetError());
        SDL_FreeSurface(surface);
        return;
    }
    int tw = surface->w;
    int th = surface->h;
    SDL_FreeSurface(surface);
    SDL_Rect dst;
    dst.w = tw;
    dst.h = th;
    dst.x = (SCREEN_WIDTH - tw) / 2;
    dst.y = y;
    SDL_RenderCopy(renderer, texture, NULL, &dst);
    SDL_DestroyTexture(texture);
}